spring:
  application:
    name: squadfy

  data:
    redis:
      host: "redis-18199.crce202.eu-west-3-1.ec2.redns.redis-cloud.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 18199
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.whuvrfyzegghgckbciuz
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    host: smtp.mailgun.org
    username: postmaster@sandbox7c8ea83d9ec34476ba4d94ea9e7bf98c.mailgun.org
    port: 587
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: seal.lmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: twaazkej
    ssl:
      enabled: true
    virtual-host: twaazkej
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 1000ms
          max-attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET_BASE64}
  expiration-minutes: 15

squadfy:
  rate-limit:
    ip:
      apply-limit: false
  email:
    from: postmaster@sandbox7c8ea83d9ec34476ba4d94ea9e7bf98c.mailgun.org
    to: freyiloijeiyi-4579@yopmail.com
    url: "http://localhost:8080"
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30
  web-socket:
    allowed-origin: "http://localhost:8080"

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost"
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)

supabase:
  url: "https://aws-1-eu-west-3.pooler.supabase.com"
  service-key: ${SUPABASE_SERVICE_KEY}