spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: postmaster@sandbox7c8ea83d9ec34476ba4d94ea9e7bf98c.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

squadfy:
  email:
    url: "https://www.kikepb.com"
  rate-limit:
    ip:
      apply-limit: true